services:
  - type: web
    name: volguard-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: UPSTOX_CLIENT_ID
        sync: false
      - key: UPSTOX_CLIENT_SECRET
        sync: false
      - key: UPSTOX_REDIRECT_URI
        sync: false
